### ISSUE TITLE
stop押した直後にreset押すと音が無限になり続ける

### ISSUE THREAD

**Issue by showyama** [w-shimaya/UTTTimer#6]
カウントしてる状態からstop押して止めてほぼ同時にreset押して00:00にしようとしたら音が無限になり続ける。
音はピーーーーじゃなくてピー、ピー、ピーって感じ。鳴り続けてても動作はするのでそのまま再びカウントさせてみると30秒のときにピーーーーーに変わった。

**Comment by w-shimaya** [comment]
#8 
ブザーを鳴らし終わったら`buzzer_state`を`prev_buz_state`に戻す」ということをしていた
-> ボタンの音が鳴っている間にさらにボタンを押すと`buzzer_state`も`prev_buzzer_state`も `Button`になって永遠に鳴り続ける？

対処：
* `buzzer_state`をstackで保持する（まだ）
* `buzzer()`に変な入力が来たケースをハンドル
  * これだけでも無限に鳴る問題はなくなる……と思う

**Comment by w-shimaya** [comment]
> * `buzzer_state`をstackで保持する
> * `buzzer()`に変な入力が来たケースをハンドル

終わり，チェックよろしく～
